name: Actions Workflow

on:
  repository_dispatch:
    types: [build]
  

jobs: 
   run-github-actions:
    runs-on: ubuntu-latest
    steps:
     - name: List Files
       run: |
         pwd
         ls -a 
         echo $GITHUB_SHA 
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo "${{ github.token }}"