name: Container

on: push

jobs:
  node-docker: 
    runs-on: ubuntu-latest
    container: node:16.8.0-alpine:3.15
    steps:
      - name: Log Node Version 
        run: |
          node -v 
          cat /etc/os-release
        